#!/usr/bin/env bash
# Install NGNINX an start service
apt-get -y update
apt-get -y install nginx
sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default
service nginx start
