#!/usr/bin/env bash
# Make a backup of database
mysqldump --all-databases --single-transaction --quick --lock-tables=false > backup.sql -u root --password="$1"
tar -czvf "$(date + "%d-%m-%Y").tar.gz" ./backup.sql
