#!/usr/bin/env bash
#Print holberton school with until statement

i=1
while [ $i -lt 11 ]
do
   if [ $i -eq 9 ]
   then
       echo "Hi"
   else
       echo "Holberton School"
   fi
   i=$((i + 1))
done
